#!/usr/bin/env bash
# Clone or update all QuantMetrics repos under one parent folder and write orchestrator/.env
# with sibling paths (quantbuildv1 / quantbridgev1 / quantlogv1).
#
# Usage:
#   chmod +x scripts/clone_quant_suite.sh
#   ./scripts/clone_quant_suite.sh
#   QUANT_SUITE_ROOT=~/dev/quant ./scripts/clone_quant_suite.sh
#   GITHUB_USER=roelofgootjesgit QUANTBUILD_BRANCH=v2-development ./scripts/clone_quant_suite.sh
#
# VS Code: open quantmetrics_os/vscode/quant-suite.code-workspace (sibling folders as in this layout).

set -euo pipefail

GITHUB_USER="${GITHUB_USER:-roelofgootjesgit}"
QUANT_SUITE_ROOT="${QUANT_SUITE_ROOT:-${HOME}/quant_suite}"
QUANTBUILD_BRANCH="${QUANTBUILD_BRANCH:-v2-development}"

REPO_METRICS="https://github.com/${GITHUB_USER}/quantmetrics_os.git"
REPO_BUILD="https://github.com/${GITHUB_USER}/quantbuildE1.git"
REPO_BRIDGE="https://github.com/${GITHUB_USER}/quantBridge-v.1.git"
REPO_LOG="https://github.com/${GITHUB_USER}/quantlog-v.1.git"

mkdir -p "${QUANT_SUITE_ROOT}"
cd "${QUANT_SUITE_ROOT}"

clone_or_pull() {
  local url="$1" dir="$2"
  if [[ -d "${dir}/.git" ]]; then
    echo "==> git pull ${dir}"
    git -C "${dir}" pull --ff-only
  else
    echo "==> git clone ${url} -> ${dir}"
    git clone "${url}" "${dir}"
  fi
}

clone_or_pull "${REPO_METRICS}" quantmetrics_os
clone_or_pull "${REPO_BUILD}" quantbuildv1
clone_or_pull "${REPO_BRIDGE}" quantbridgev1
clone_or_pull "${REPO_LOG}" quantlogv1

echo "==> checkout QuantBuild branch ${QUANTBUILD_BRANCH}"
git -C quantbuildv1 fetch origin "${QUANTBUILD_BRANCH}" || true
if git -C quantbuildv1 show-ref --verify --quiet "refs/remotes/origin/${QUANTBUILD_BRANCH}"; then
  git -C quantbuildv1 checkout "${QUANTBUILD_BRANCH}" 2>/dev/null \
    || git -C quantbuildv1 checkout -B "${QUANTBUILD_BRANCH}" "origin/${QUANTBUILD_BRANCH}"
else
  echo "Warning: origin/${QUANTBUILD_BRANCH} not found; staying on current branch in quantbuildv1"
fi

ENV_FILE="${QUANT_SUITE_ROOT}/quantmetrics_os/orchestrator/.env"
ORCH_EXAMPLE="${QUANT_SUITE_ROOT}/quantmetrics_os/orchestrator/config.example.env"
if [[ ! -f "${ORCH_EXAMPLE}" ]]; then
  echo "Missing ${ORCH_EXAMPLE}" >&2
  exit 1
fi

PYTHON_BIN="python3"
if ! command -v python3 >/dev/null 2>&1; then
  PYTHON_BIN="python"
fi

cat > "${ENV_FILE}" <<EOF
# Generated by scripts/clone_quant_suite.sh — edit if your layout differs.
QUANTBUILD_ROOT=${QUANT_SUITE_ROOT}/quantbuildv1
QUANTBRIDGE_ROOT=${QUANT_SUITE_ROOT}/quantbridgev1
QUANTLOG_ROOT=${QUANT_SUITE_ROOT}/quantlogv1
PYTHON=${PYTHON_BIN}
QUANTBUILD_CONFIG=configs/strict_prod_v2.yaml
QUANTBRIDGE_CONFIG=configs/ctrader_icmarkets_demo.yaml
EOF

echo ""
echo "Wrote ${ENV_FILE}"
echo ""
echo "Layout:"
echo "  ${QUANT_SUITE_ROOT}/quantmetrics_os"
echo "  ${QUANT_SUITE_ROOT}/quantbuildv1   (branch: $(git -C quantbuildv1 branch --show-current 2>/dev/null || echo '?'))"
echo "  ${QUANT_SUITE_ROOT}/quantbridgev1"
echo "  ${QUANT_SUITE_ROOT}/quantlogv1"
echo ""
echo "Check orchestrator:"
echo "  cd ${QUANT_SUITE_ROOT}/quantmetrics_os && python orchestrator/quantmetrics.py check"
echo ""
echo "VS Code: File → Open Workspace from File…"
echo "  ${QUANT_SUITE_ROOT}/quantmetrics_os/vscode/quant-suite.code-workspace"
